# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ServiceRequest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ServiceRequest
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'MessageKit'
  pod 'Kanna'

  target 'ServiceRequestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ServiceRequestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
